import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./compnents/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter Clone App",
  description: "Generated by Zaheer Khan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
